export const lgaOptions = {
  "Abia state": [
    "Bende",
    "Ikwuano",
    "Aba North",
    "Aba South",
    "Arochukwu",
    "Isiala Ngwa North",
    "Isiala Ngwa South LGA",
    "Isuikwuato",
    "Obi Ngwa",
    "Ohafia LGA",
    "Osisioma Ngwa LGA",
    "Ugwunagbo LGA",
    "Ukwa East LGA",
    "Ukwa West LGA",
    "Umuahia North LGA",
    "Umuahia South LGA",
    "Umu Nneochi LGA",
  ],
  "Adamawa State": [
    "Girei LGA",
    "Gombi LGA",
    "Jada LGA",
    "Demsa LGA",
    "Fufore LGA",
    "Ganye LGA",
    "Lamurde LGA",
    "Madagali LGA",
    "Maiha LGA",
    "Mayo-Belwa LGA",
    "Guyuk LGA",
    "Hong LGA",
    "Michika LGA",
    "Numan LGA",
    "Shelleng LGA",
    "Song LGA",
    "Mubi North LGA",
    "Mubi South LGA",
    "Toungo LGA",
    "Yola North LGA",
    "Yola South LGA",
  ],
  "Akwa Ibom State": [
    "Ikono LGA",
    "Eket LGA",
    "Esit-Eket LGA",
    "Abak LGA",
    "Eastern Obolo LGA",
    "Ibesikpo-Asutan LGA",
    "Ibeno LGA",
    "Ibiono-Ibom LGA",
    "Ika LGA",
    "Essien Udim LGA",
    "Etim-Ekpo LGA",
    "Etinan LGA",
    "Nsit-Atai LGA",
    "Nsit-Ibom LGA",
    "Nsit-Ubium LGA",
    "Obot-Akara LGA",
    "Ini LGA",
    "Itu LGA",
    "Mbo LGA",
    "Mkpat-Enin LGA",
    "Ikot Abasi LGA",
    "Ikot Ekpene LGA",
    "Okobo LGA",
    "Onna LGA",
    "Oron LGA",
    "Oruk Anam LGA",
    "Urue-Offong/Oruko LGA",
    "Uyo LGA",
    "Ukanafun LGA",
    "Udung-Uko LGA",
    "Uruan LGA",
  ],
  "Anambra State": [
    "Aguata LGAs",
    "Anambra East LGA",
    "Anambra West LGA",
    "Anaocha LGA",
    "Ayamelum LGA",
    "Awka North LGA",
    "Awka South LGA",
    "Ihiala LGA",
    "Njikoka LGA",
    "Nnewi North LGA",
    "Nnewi South LGA",
    "Dunukofia LGA",
    "Ekwusigo LGA",
    "Idemili North LGA",
    "Idemili South LGA",
    "Ogbaru LGA",
    "Onitsha North LGA",
    "Onitsha South LGA",
    "Orumba North LGA",
    "Orumba South LGA",
    "Oyi LGA",
  ],
  "Bauchi State": [
    "Bogoro LGA",
    "Ningi LGA",
    "Warji LGA",
    "Dass LGA",
    "Toro LGA",
    "Ganjuwa LGA",
    "Kirfi LGA",
    "Alkaleri LGA",
    "Bauchi LGA",
    "Tafawa Balewa LGA",
    "Darazo LGA",
    "Misau LGA",
    "Katagum LGA",
    "Itas/Gadau LGA",
    "Giade LGA",
    "Shira LGA",
    "Jama'are LGA",
    "Zaki LGA",
    "Gamawa LGA",
    "Damban LGA",
  ],
  "Bayelsa State ": [
    "Kolokuma/Opokuma LGA",
    "Nembe LGA",
    "Ogbia LGA",
    "Sagbama LGA",
    "Brass LGA",
    "Ekeremor LGA",
    "Southern Ijaw LGA",
    "Yenagoa LGA",
  ],
  "Benue State": [
    "Guma LGA",
    "Gwer East LGA",
    "Gwer West LGA",
    "Katsina-Ala LGA",
    "Konshisha LGA",
    "Ado LGA",
    "Buruku LGA",
    "Gboko LGA",
    "Kwande LGA",
    "Logo LGA",
    "Makurdi LGA",
    "Obi LGA",
    "Ogbadibo LGA",
    "Ohimini LGA",
    "Oju LGA",
    "Agatu LGA",
    "Apa LGA",
    "Okpokwu LGA",
    "Otukpo LGA",
    "Tarka LGA",
  ],
  "Borno State": [
    "Bayo LGA",
    "Biu LGA",
    "Chibok LGA",
    "Damboa LGA",
    "Dikwagubio LGA",
    "Guzamala LGA",
    "Abadan LGA",
    "Askira/Uba LGA",
    "Bama LGA",
    "Gwoza LGA",
    "Ukum LGA",
    "Ushongo LGA",
    "Vandeikya LGA",
    "Kalka/Balge LGA",
    "Maiduguri LGA",
    "Marte LGA",
    "Mobbar LGA",
    "Monguno LGA",
    "Konduga LGA",
    "Kukawa LGA",
    "Borno State",
    "Hawul LGA",
    "Jere LGA",
    "Kaga LGA",
    "Kwaya-ku LGA",
    "Mafa LGA",
    "Magumeri LGA",
    "Ngala LGA",
    "Nganzai LGA",
    "Shani LGA",
  ],
  "Cross River State": [
    "Calabar Municipal LGA",
    "Calabar South LGA",
    "Etung LGA",
    "Ikom LGA",
    "Obanliku LGA",
    "Abi LGA",
    "Akamkpa LGA",
    "Biase LGA",
    "Boki LGA",
    "Obubra LGA",
    "Obudu LGA",
    "Odukpani LGA",
    "Akpabuyo LGA",
    "Bakassi LGA",
    "Bekwarra LGA",
    "Ogoja LGA",
    "Yakuur LGA",
    "Yala LGA",
  ],
  "Delta State": [
    "Ethiope west LGA",
    "Ethiope east LGA",
    "Ika south LGA",
    "Ika north east LGA",
    "Isoko south LGA",
    "Isoko north LGA",
    "Aniocha south LGA",
    "Anioha LGA",
    "Bomadi LGA",
    "Burutu LGA",
    "Ukwuani LGA",
    "Uviwie LGA",
    "Warri central LGA",
    "Warri north LGA",
    "Warri south LGA",
    "Okpe LGA",
    "Oshimili north LGA",
    "Oshimili south LGA",
    "Patani LGA",
    "Sapele LGA",
    "Ndokwa east LGA",
    "Ndokwa west LGA",
    "Udu LGA",
    "Ughelli south LGA",
    "Ughelli north LGA",
  ],
  "Ebonyi State": [
    "Izzi LGA",
    "Abakaliki LGA",
    "Ezza North LGA",
    "Ivo LGA",
    "Afikpo South (Edda) LGA",
    "Ohaozara LGA",
    "Afikpo North LGA",
    "Ebonyi LGA",
    "Ohaukwu LGA",
    "Onicha LGA",
  ],
  "Enugu State": [
    "Ezza South LGA",
    "Ikwo LGA",
    "Igbo Eze South LGA",
    "Aninri LGA",
    "Awgu LGA",
    "Isi Uzo LGA",
    "Nkanu East LGA",
    "Nkanu West LGA",
    "Nsukka LGA",
    "Ishielu LGA",
    "Enugu East LGA",
    "Enugu North LGA",
    "Enugu South LGA",
    "Oji River LGA",
    "Udenu LGA",
    "Udi LGA",
    "Ezeagu LGA",
    "Igbo Etiti LGA",
    "Igbo Eze North LGA",
    "Uzo-Uwani LGA",
  ],
  "Edo State": [
    "Igueben LGA",
    "Ikpoba-Okha LGA",
    "Oredo LGA",
    "Akoko-Edo LGA",
    "Egor LGA",
    "Esan Central LGA",
    "Esan North-East LGA",
    "Esan South-East LGA",
    "Esan West LGA",
    "Orhionmwon LGA",
    "Ovia North-East LGA",
    "Ovia South-West LGA",
    "Etsako Central LGA",
    "Etsako East LGA",
    "Etsako West LGA",
    "Owan East LGA",
    "Owan West LGA",
    "Uhunmwonde LGA",
  ],
  "Ekiti State": [
    "Efon LGA",
    "Emure LGA",
    "Ido-Osi LGA",
    "Ijero LGA",
    "Ado-Ekiti LGA",
    "Ikere LGA",
    "Oye LGA",
    "Aiyekire (Gbonyin) LGA",
    "Ikole LGA",
    "Ilejemeje LGA",
    "Irepodun/Ifelodun LGA",
    "Ekiti East LGA",
    "Ekiti South-West LGA",
    "Ekiti West LGA",
    "Ise/Orun LGA",
    "Moba LGA",
  ],
  "Gombe State": [
    "Akko LGA",
    "Balanga LGA",
    "Billiri LGA",
    "Dukku LGA",
    "Dunakaye LGA",
    "Gombe LGA",
    "Kaltungo LGA",
    "Kwami LGA",
    "Nafada/Bajoga LGA",
    "Shomgom LGA",
    "Yamaltu/Deba LGA",
  ],
  "Imo State Imo": [
    "Ezinihitte Mbaise LGA",
    "Ideato North LGA",
    "Ideato South LGA",
    "Ihitte/Uboma LGA",
    "Aboh Mbaise LGA",
    "Ahiazu Mbaise LGA",
    "Ehime Mbano LGA",
    "Njaba LGA",
    "Nkwerre LGA",
    "Nwangele LGA",
    "Obowo LGA",
    "Oguta LGA",
    "Ikeduru LGA",
    "Isiala Mbano LGA",
    "Isu LGA",
    "Mbaitoli LGA",
    "Ngor Okpala LGA",
    "Ohaji/Egbema LGA",
    "Oru East LGA",
    "Oru West LGA",
    "Owerri Municipal LGA",
    "Okigwe LGA",
    "Onuimo LGA",
    "Orlu LGA",
    "Orsu LGA",
    "Owerri North LGA",
    "Owerri West LGA",
    "Nwangele LGA",
  ],
  "Jigawa State": [
    "Buji LGA",
    "Dutse LGA",
    "Gagarawa LGA",
    "Garki LGA",
    "Gumel LGA",
    "Guri LGA",
    "Gwaram LGA",
    "Gwiwa LGA",
    "Auyo LGA",
    "Babura LGA",
    "Biriniwa LGA",
    "Birnin Kudu LGA",
    "Hadejia LGA",
    "Jahun LGA",
    "Kafin Hausa LGA",
    "Kaugama LGA",
    "Kazaure LGA",
    "Kiri Kasama LGA",
    "Kiyawa LGA",
    "Maigatari LGA",
    "Malam Madori LGA",
    "Miga LGA",
    "Ringim LGA",
    "Roni LGA",
    "Sule Tankarkar LGA",
    "Taura LGA",
    "Yankwashi LGA",
  ],
  "Kaduna State": [
    "Kaduna North LGA",
    "Kaduna South LGA",
    "Birnin Gwari LGA",
    "Chikun LGA",
    "Giwa LGA",
    "Igabi LGA",
    "Kagarko LGA",
    "Kajuru LGA",
    "Kaura LGA",
    "Kauru LGA",
    "Kubau LGA",
    "Kudan LGA",
    "Ikara LGA",
    "Jaba LGA",
    "Jema’a LGA",
    "Kachia LGA",
    "Lere LGA",
    "Makarfi LGA",
    "Soba LGA",
    "Zangon Kataf LGA",
    "Sabon Gari LGA",
    "Sanga LGA",
    "Zaria LGA",
  ],
  "Kano State": [
    "Ajingi LGA",
    "Albasu LGA",
    "Minjibir LGA",
    "Nassarawa LGA",
    "Rano LGA",
    "Bagwai LGA",
    "Bebeji LGA",
    "Bichi LGA",
    "Dawakin Tofa LGA",
    "Doguwa LGA",
    "Fagge LGA",
    "Gabasawa LGA",
    "Garko LGA",
    "Garun Mallam LGA",
    "Gaya LGA",
    "Gezawa LGA",
    "Gwale LGA",
    "Gwarzo LGA",
    "Bunkure LGA",
    "Dala LGA",
    "Dambatta LGA",
    "Dawakin kudu LGA",
    "Kabo LGA",
    "Kano Municipal LGA",
    "Karaye LGA",
    "Kibiya LGA",
    "Kiru LGA",
    "Kumbtso LGA",
    "Kunchi LGA",
    "Kura LGA",
    "Madobi LGA",
    "Makoda LGA",
    "Rimin Gado LGA",
    "Rogo LGA",
    "Shanono LGA",
    "Sumaila LGA",
    "Takai LGA",
    "Tarauni LGA",
    "Tofa LGA",
    "Tsanyawa LGA",
    "Tudun Wada LGA",
    "Ungogo LGA",
    "Warawa LGA",
    "Wudil LGA",
  ],
  "Katsina State": [
    "Bindawa LGA",
    "Charanchi LGA",
    "Dan Musa LGA",
    "Dandume LGA",
    "Danja LGA",
    "Bakori LGA",
    "Batagarawa LGA",
    "Batsari LGA",
    "Baure LGA",
    "Daura LGA",
    "Dutsi LGA",
    "Jibia LGA",
    "Kafur LGA",
    "Kaita LGA",
    "Kankara LGA",
    "Dutsin-Ma LGA",
    "Faskari LGA",
    "Funtua LGA",
    "Ingawa LGA",
    "Kankia LGA",
    "Katsina LGA",
    "Kurfi LGA",
    "Kusada LGA",
    "Mai'Adua LGA",
    "Malumfashi LGA",
    "Mani LGA",
    "Mashi LGA",
    "Matazu LGA",
    "Musawa LGA",
    "Rimi LGA",
    "Sabuwa LGA",
    "Safana LGA",
    "Sandamu LGA",
    "Zango LGA",
  ],
  "Kebbi State": [
    "Dandi LGA",
    "Fakai LGA",
    "Gwandu LGA",
    "Jega LGA",
    "Arewa Dandi LGA",
    "Argungu LGA",
    "Augie LGA",
    "Kalgo LGA",
    "Sakaba LGA",
    "Shanga LGA",
    "Suru LGA",
    "Koko/Besse LGA",
    "Maiyama LGA",
    "Ngaski LGA",
    "Danko/Wasagu LGA",
    "Yauri LGA",
    "Zuru LGA",
    "Aleiro LGA",
    "Bagudo LGA",
    "Birnin Kebbi LGA",
    "Bunza LGA",
  ],
  "Kogi State": [
    "Dekina LGA",
    "Ibaji LGA",
    "Idah LGA",
    "Igalamela-Odolu LGA",
    "Adavi LGA",
    "Ajaokuta LGA",
    "Ankpa LGA",
    "Bassa LGA",
    "Ijumu LGA",
    "Ofu LGA",
    "Ogori/Magongo LGA",
    "Okehi LGA",
    "Okene LGA",
    "Olamaboro LGA",
    "Kabba/Bunu LGA",
    "Koton Karfe LGA",
    "Lokoja LGA",
    "Mopa-Muro LGA",
    "Omala LGA",
    "Yagba East LGA",
    "Yagba West LGA",
  ],
  "Kwara State": [
    "Ilorin East LGA",
    "Ilorin South LGA",
    "Ilorin West LGA",
    "Ifelodun LGA",
    "Irepodun LGA",
    "Isin LGA",
    "Kaiama LGA",
    "Moro LGA",
    "Asa LGA",
    "Baruten LGA",
    "Edu LGA",
    "Ekiti LGA",
    "Offa LGA",
    "Oke Ero LGA",
    "Oyun LGA",
    "Pategi LGA",
  ],
  "Lagos State": [
    "Apapa LGA",
    "Mushin LGA",
    "Ojo LGA",
    "Oshodi Isolo LGA",
    "Shomolu LGA",
    "Surulere LGA",
    "Badagry LGA",
    "Epe LGA",
    "Eti-Osa LGA",
    "Ibeju- Lekki LGA",
    "Ifako/Ijaye LGA",
    "Ikeja LGA",
    "Agege LGA",
    "Alimosho Ifelodun LGA",
    "Alimosho LGA",
    "Amuwo-Odofin LGA",
    "Ikorodu LGA",
    "Kosofe LGA",
    "Lagos Island LGA",
    "Lagos Mainland LGA",
  ],
  "Nasarawa State": [
    "Karu LGA",
    "Nassarawa LGA",
    "Nassarawa/Eggon LGA",
    "Obi LGA",
    "Toto LGA",
    "Wamba LGA",
    "Keana LGA",
    "Keffi LGA",
    "Kokona LGA",
    "Akwanga LGA",
    "Awe LGA",
    "Doma LGA",
    "Lafia LGA",
  ],
  "Niger State": [
    "Gurara LGA",
    "Katcha LGA",
    "Bosso LGA",
    "Chanchaga LGA",
    "Edati LGA",
    "Gbako LGA",
    "Bida LGA",
    "Borgu LGA",
    "Lapai LGA",
    "Lavun LGA",
    "Kontagora LGA",
    "Agaie LGA",
    "Agwara LGA",
    "Rafi LGA",
    "Magama LGA",
    "Mariga LGA",
    "Mashegu LGA",
    "Mokwa LGA",
    "Rijau LGA",
    "Shiroro LGA",
    "Suleja LGA",
    "Munya LGA",
    "Paikoro LGA",
    "Tafa LGA",
    "Wushishi LGA",
  ],
  "Ogun State": [
    "Ifo LGA",
    "Ijebu East LGA",
    "Ijebu North LGA",
    "Ijebu North East LGA",
    "Abeokuta North LGA",
    "Abeokuta South LGA",
    "Ado-Odo/Ota LGA",
    "Imeko Afon LGA",
    "Ipokia LGA",
    "Obafemi Owode LGA",
    "Odogbolu LGA",
    "Sagamu LGA",
    "Yewa North LGA",
    "Yewa South LGA",
    "Ewekoro LGA",
    "Ijebu Ode LGA",
    "Ikenne LGA",
    "Odeda LGA",
    "Ogun Waterside LGA",
    "Remo North LGA",
  ],
  "Ondo State": [
    "Akoko north LGA",
    "Akoko north east LGA",
    "Akoko south east LGA",
    "Ondo LGA",
    "Ondo east LGA",
    "Ose LGA",
    "Owo LGA",
    "Akoko south LGA",
    "Akure north LGA",
    "Akure LGA",
    "Idanre LGA",
    "Irele LGA",
    "Odigbo LGA",
    "Okitipupa LGA",
    "Ifedore LGA",
    "Ese Odo LGA",
    "Ilaje LGA",
    "Ile Oluji/Okeigbo LGA",
  ],
  "Osun State": [
    "Bolawaduro LGA",
    "Boripe LGA",
    "Ede LGA",
    "Ede north LGA",
    "Atakumosa west LGA",
    "Atakumosa east LGA",
    "Ayedaade LGA",
    "Ayedire LGA",
    "Ife south LGA",
    "Ife east LGA",
    "Ifedayo, Ifelodun LGA",
    "Ilesha west LGA",
    "Egbedore LGA",
    "Ejigbo LGA",
    "Ife north LGA",
    "Ife central LGA",
    "Ila- orangun LGA",
    "Ilesah east LGA",
    "Irepodun LGA",
    "ola oluwa LGA",
    "olorunda LGA",
    "Oriade LGA, Orolu LGA",
    "Osogbo LGA",
    "Irewole LGA",
    "Isokan LGA",
    "Iwo LGA",
    "Obokun LGA",
    "Odo-otin LGA",
  ],
  "Oyo State": [
    "Akinyele Moniya LGA",
    "Afijio Jobele LGA",
    "Ido LGA",
    "Irepo LGA",
    "Iseyin LGA",
    "Egbeda Egbeda LGA",
    "Ibadan North Agodi Gate LGA",
    "Ibadan North-East Iwo Road LGA",
    "Ibadan North-West LGA",
    "Ibadan South-West Ring Road LGA",
    "Ibadan South-East Mapo LGA",
    "Ibarapa Central LGA",
    "Ibarapa East Eruwa LGA",
    "Kajola LGA",
    "Lagelu LGA",
    "Atisbo Tede LGA",
    "Saki West LGA",
    "Saki East LGA",
    "Ogbomosho North LGA",
    "Ogbomosho South LGA",
    "Oyo West Ojongbodu LGA",
    "Atiba Ofa Meta LGA",
    "Itesiwaju Otu LGA",
    "Iwajowa LGA",
    "Surulere LGA",
    "Orelope LGA",
    "Ori Ire LGA",
    "Ibarapa North LGA",
    "Olorunsogo LGA",
    "Oluyole LGA",
    "Ogo Oluwa LGA",
    "Oyo East LGA",
    "Ona Ara LGA",
  ],
  "Plateau State": [
    "Bokkos LGA",
    "Jos East LGA",
    "Kanam LGA",
    "Barkin Ladi LGA",
    "Bassa LGA",
    "Kanke LGA",
    "Langtang North LGA",
    "Jos North LGA",
    "Jos South LGA",
    "Langtang South LGA",
    "Riyom LGA",
    "Shendam LGA",
    "Wase LGA",
    "Mangu LGA",
    "Mikang LGA",
    "Pankshin LGA",
    "Qua'an Pan LGA",
  ],
  "Rivers State": [
    "Abua-Odual LGA",
    "Ahoada East LGA",
    "Asari-Toru LGA",
    "Bonny LGA",
    "Etche LGA",
    "Gokana LGA",
    "Ikwerre LGA",
    "Degema LGA",
    "Ahoada West LGA",
    "Akuku-Toru LGA",
    "Andoni LGA",
    "Eleme LGA",
    "Emohua LGA",
    "Oyigbo LGA",
    "Khana LGA",
    "Omumma LGA",
    "Opobo-Nkoro LGA",
    "Portharcourt LGA",
    "Tai LGA",
    "Obio-Akpor LGA",
    "Ogba-Egbema-Ndoni LGA",
    "Ogu-bolo LGA",
    "Okrika LGA",
  ],
  "Sokoto State": [
    "Gada LGA",
    "Isa LGA",
    "Kebbe LGA",
    "Kware LGA",
    "Rabah LGA",
    "Goronyo LGA",
    "Gudu LGA",
    "Gwadabawa LGA",
    "Illela LGA",
    "Sabon Birni LGA",
    "Binji LGA",
    "Bodinga LGA",
    "Dange Shuni LGA",
    "Shagari LGA",
    "Tureta LGA",
    "Wamako LGA",
    "Wurno LGA",
    "Yabo LGA",
    "Silame LGA",
    "Sokoto North LGA",
    "Sokoto South LGA",
    "Tambuwal LGA",
    "Tangaza LGA",
  ],
  "Taraba State": [
    "Ardo Kola LGA",
    "Bali LGA",
    "Gassol LGA",
    "Ibi LGA",
    "Jalingo LGA",
    "Donga LGA",
    "Gashaka LGA",
    "Karim Lamido LGA",
    "Kurmi LGA",
    "Wukari LGA",
    "Yorro LGA",
    "Zing LGA",
    "Lau LGA",
    "Sardauna LGA",
    "Takum LGA",
    "Ussa LGA",
  ],
  "Yobe State": [
    "Fune LGA",
    "Jakusko LGA",
    "Karasuwa LGA",
    "Machina LGA",
    "Bade LGA",
    "Bursari LGA",
    "Damaturu LGA",
    "Geidam LGA",
    "Gujba LGA",
    "Potiskum LGA",
    "Tarmuwa LGA",
    "Gulani LGA",
    "Fika LGA",
    "Nangere LGA",
    "Nguru LGA",
    "Yunusari LGA",
    "Yusufari LGA",
  ],
  "Zamfara State": [
    "Bungudu LGA",
    "Tsafe LGA",
    "Shinkafi LGA",
    "Talata Mafara LGA",
    "Zurmi LGA",
    "Anka LGA",
    "Bakura LGA",
    "Birnin Magaji/Kiyaw LGA",
    "Bukkuyum LGA",
    "Gummi LGA",
    "Gusau LGA",
    "Kaura Namoda LGA",
    "Maradun LGA",
    "Maru LGA",
  ],
  "Federal Capital Territory Abuja": [
    "Gwagwalada LGA",
    "Kuje LGA",
    "Bwari LGA",
    "Abaji LGA",
    "Abuja Municipa LGA",
    "Kwali",
  ],
};
